### ISSUE TITLE
KubevirtCluster not "ready" and cluster stuck in provisioning for a long time 

### ISSUE THREAD

**Issue by salilhpe** [kubernetes-sigs/cluster-api-provider-kubevirt#172] opened 2022-08-10 01:06 UTC
**What steps did you take and what happened:**
I have a 3 server management cluster (with Ubuntu 20.04 and microk8s 1.21/stable)
Have CAPI 1.2.0, Kubevirt 0.5.5 and latest release version of CAPK i.e. v0.1.0 
then I create a new cluster with the following arguments to clusterctl:

export IMAGE_REPO=k8s.gcr.io
export NODE_VM_IMAGE_TEMPLATE=quay.io/capk/ubuntu-2004-container-disk:v1.22.0
export CRI_PATH=/var/run/containerd/containerd.sock
clusterctl generate cluster ccstest01 --kubernetes-version v1.22.0 --control-plane-machine-count=5 --worker-machine-count=5 --target-namespace ccs-test --from templates/cluster-template.yaml

After deploying the cluster stays in provisioning state :
$ kubectl get clusters -n ccs-test
NAME        PHASE          AGE    VERSION
ccstest01   Provisioning   5m8s

and Kubevirtcluster has no Ready status:

$ kubectl get  -n ccs-test kubevirtcluster -o yaml
apiVersion: v1
items:
- apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
  kind: KubevirtCluster
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"infrastructure.cluster.x-k8s.io/v1alpha1","kind":"KubevirtCluster","metadata":{"annotations":{},"name":"ccstest01","namespace":"ccs-test"},"spec":{"controlPlaneServiceTemplate":{"spec":{"type":"ClusterIP"}}}}
    creationTimestamp: "2022-08-10T00:39:05Z"
    finalizers:
    - kubevirtcluster.infrastructure.cluster.x-k8s.io
    generation: 2
    labels:
      cluster.x-k8s.io/cluster-name: ccstest01
    name: ccstest01
    namespace: ccs-test
    ownerReferences:
    - apiVersion: cluster.x-k8s.io/v1beta1
      blockOwnerDeletion: true
      controller: true
      kind: Cluster
      name: ccstest01
      uid: ea09b2b9-1787-4408-97c6-193c5c96afa3
    resourceVersion: "3751834"
    selfLink: /apis/infrastructure.cluster.x-k8s.io/v1alpha1/namespaces/ccs-test/kubevirtclusters/ccstest01
    uid: 362816a7-03e3-4735-bf33-730213f35dec
  spec:
    controlPlaneEndpoint:
      host: 10.152.183.226
      port: 6443
    controlPlaneServiceTemplate:
      spec:
        type: ClusterIP
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

In the capk-controller logs I see the following lines repeated:

E0810 00:39:26.463301       1 controller.go:317] controller/kubevirtcluster "msg"="Reconciler error" "error"="failed to persist ssh keys to secret: failed to set owner reference for secret: Operation cannot be fulfilled on secrets \"ccstest01-ssh-keys\": the object has been modified; please apply your changes to the latest version and try again" "name"="ccstest01" "namespace"="ccs-test" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="KubevirtCluster" 
E0810 00:39:46.964172       1 kubevirtcluster_controller.go:118] controller/kubevirtcluster/ccs-test/ccstest01 "msg"="failed to patch KubevirtCluster" "error"="KubevirtCluster.infrastructure.cluster.x-k8s.io \"ccstest01\" is invalid: status.ready: Required value" "name"="ccstest01" "namespace"="ccs-test" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="KubevirtCluster" 
E0810 00:39:46.964218       1 controller.go:317] controller/kubevirtcluster "msg"="Reconciler error" "error"="failed to persist ssh keys to secret: failed to set owner reference for secret: Operation cannot be fulfilled on secrets \"ccstest01-ssh-keys\": the object has been modified; please apply your changes to the latest version and try again" "name"="ccstest01" "namespace"="ccs-test" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="KubevirtCluster" 
E0810 00:40:27.950044       1 kubevirtcluster_controller.go:118] controller/kubevirtcluster/ccs-test/ccstest01 "msg"="failed to patch KubevirtCluster" "error"="KubevirtCluster.infrastructure.cluster.x-k8s.io \"ccstest01\" is invalid: status.ready: Required value" "name"="ccstest01" "namespace"="ccs-test" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="KubevirtCluster" 
E0810 00:40:27.950130       1 controller.go:317] controller/kubevirtcluster "msg"="Reconciler error" "error"="failed to persist ssh keys to secret: failed to set owner reference for secret: Operation cannot be fulfilled on secrets \"ccstest01-ssh-keys\": the object has been modified; please apply your changes to the latest version and try again" "name"="ccstest01" "namespace"="ccs-test" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="KubevirtCluster" 
E0810 00:41:49.904838       1 kubevirtcluster_controller.go:118] controller/kubevirtcluster/ccs-test/ccstest01 "msg"="failed to patch KubevirtCluster" "error"="KubevirtCluster.infrastructure.cluster.x-k8s.io \"ccstest01\" is invalid: status.ready: Required value" "name"="ccstest01" "namespace"="ccs-test" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="KubevirtCluster" 
E0810 00:41:49.904890       1 controller.go:317] controller/kubevirtcluster "msg"="Reconciler error" "error"="failed to persist ssh keys to secret: failed to set owner reference for secret: Operation cannot be fulfilled on secrets \"ccstest01-ssh-keys\": the object has been modified; please apply your changes to the latest version and try again" "name"="ccstest01" "namespace"="ccs-test" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="KubevirtCluster" 
E0810 00:44:33.769811       1 kubevirtcluster_controller.go:118] controller/kubevirtcluster/ccs-test/ccstest01 "msg"="failed to patch KubevirtCluster" "error"="KubevirtCluster.infrastructure.cluster.x-k8s.io \"ccstest01\" is invalid: status.ready: Required value" "name"="ccstest01" "namespace"="ccs-test" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="KubevirtCluster" 
E0810 00:44:33.769852       1 controller.go:317] controller/kubevirtcluster "msg"="Reconciler error" "error"="failed to persist ssh keys to secret: failed to set owner reference for secret: Operation cannot be fulfilled on secrets \"ccstest01-ssh-keys\": the object has been modified; please apply your changes to the latest version and try again" "name"="ccstest01" "namespace"="ccs-test" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="KubevirtCluster" 

I noticed that the cluster remains in this state for extended period (in multiple runs this wait ranged from 45mins to 3+ hours ) and then all of a sudden the cluster state changes and the subsequent boot strapping operations start. 

**What did you expect to happen:**
I expect the cluster to be in ready soon as it should take at most  couple of mins to setup the infra. 

**Anything else you would like to add:**
Since the state was getting resolved randomly, i.e. suddenly setting up the ownership on the ssh keys secret used to work and the cluster was all good. I suspected it to be some kind of race condition, and sure enough with the following changes my clusters were provisioned in seconds:

diff --git a/pkg/ssh/cluster_node_ssh_keys.go b/pkg/ssh/cluster_node_ssh_keys.go
index d3b6d33..80d5892 100644
--- a/pkg/ssh/cluster_node_ssh_keys.go
+++ b/pkg/ssh/cluster_node_ssh_keys.go
@@ -17,6 +17,8 @@ limitations under the License.
 package ssh
 
 import (
+       "time"
+
        "github.com/pkg/errors"
        corev1 "k8s.io/api/core/v1"
        metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
@@ -85,6 +87,9 @@ func (c *ClusterNodeSshKeys) PersistKeysToSecret() (*corev1.Secret, error) {
                return nil, errors.Wrapf(err, "failed to create ssh keys secret for cluster")
        }
 
+       // test if sleeping helps
+       time.Sleep( 10 *  time.Millisecond)
+
        // set owner reference for secret
        mutateFn := func() (err error) {
                newSecret.SetOwnerReferences(clusterutil.EnsureOwnerRef(

$ kubectl get cluster -A
NAMESPACE   NAME        PHASE         AGE   VERSION
ccs-test    ccstest01   Provisioned   8s  

**Environment:**

- Cluster-api version:  1.2.0
- Cluster-api-provider-kubevirt version: 0.1.0
- Kubernetes version: (use `kubectl version`): v1.21.14
- KubeVirt version: 0.5.5
- OS (e.g. from `/etc/os-release`): 
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt/labels?q=area for the list of labels]

**Comment by galbeniluz** [comment] 2022-08-21 11:38
From what I've experienced the problem is with the kube controller configuration, it has a --port flag which is not being accepted  so the pods in kube-system namespace are left in crashloopbackoff and that is what keeping the cluster in that state

**Comment by salilhpe** [comment] 2022-08-22 16:00
In my case the VMs were not even started,  it was stuck trying to set the Infrastructure state to ready.

**Comment by davidvossel** [comment] 2022-08-23 15:51
I think this is caused by the cluster controller doing two sequential updates on the secret within the reconcile loop. We should only be doing a single write to the ssh key in the `PersistKeysToSecret` function

**Comment by davidvossel** [comment] 2022-08-29 20:26
I've posted a potential fix for this here, https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt/pull/176

**Comment by salilhpe** [comment] 2022-09-01 02:56
> 

I tested the fix, it works for me. Converting to the single update function is what was needed !

**Closed** 2022-09-17 11:18 UTC
Labels: kind/bug
